INSERT INTO categorias (id, nombre, principal) VALUES 
(1, 'Aceites', 0),
(2, 'Cereales', 0),
(3, 'Chocolateria', 0),
(4, 'Comidas listas MOLE', 0),
(5, 'Endulzantes', 0),
(6, 'Extras', 0),
(7, 'Fideos EMILIA', 0),
(8, 'Frutos Secos', 0),
(9, 'Granolas', 0),
(10,'Granolas TUTTI GRANI', 0),
(11,'Harinas', 0),
(12,'Leche vegetal', 0),
(13,'Legumbres', 0),
(14,'Manteca clarificada GHEE', 0),
(15,'MIXS', 0),
(16,'Semillas', 0),
(17,'Snacks salados', 0),
(18,'Suplementos naturales', 0),
(19,'Untables', 0),
(20,'Yerbas', 0);